development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: temp_app_dev
  pool: 5
  host: localhost
  username: postgres
  password: password

test:
    adapter: postgresql
    encoding: utf8
    reconnect: false
    database: temp_app_test
    pool: 5
    host: localhost
    username: postgres
    password: password

# production:
#     adapter: postgresql
#     encoding: utf8
#     reconnect: false
#     database:
#     pool: 5
#     host:
#     port: 5432
#     username:
#     password: